api_platform:
    #The title of the API.
    title: 'Also API'

    #The description of the API.
    description: 'This API allows me to connect my applications to my database'

    #The version of the API.
    version: '1.0.0'


    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    collection:
        pagination:
            enabled: false
