vich_uploader:
    db_driver: orm

    mappings:
         projects_images:
            uri_prefix: /uploads/images/projects
            upload_destination: '%kernel.project_dir%/public/uploads/images/projects'
            
         articles_images:
            uri_prefix: /uploads/images/articles
            upload_destination: '%kernel.project_dir%/public/uploads/images/articles'
